[workspace.package]
version = "0.0.1"
authors = ["walleXD <github.accounts.monday392@passmail.net>"]
edition = "2024"
license = "MIT"
readme = "README.md"
rust-version = "1.89.0"

[workspace]
members = ["crates/*"]
resolver = "2"
