version: '3.8'

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - quacklake-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: quacklake
      POSTGRES_PASSWORD: quacklake
      POSTGRES_DB: quacklake_metadata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quacklake-net

networks:
  quacklake-net:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
